# Generated by Django 4.1.4 on 2024-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('entry_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, default='products/default/default-img.jpg', upload_to='products')),
            ],
        ),
    ]
